#!/bin/bash

### Display manager ###
# lightdm
lightdm_pkgs=("lightdm" "lightdm-slick-greeter" "lightdm-settings" "light-locker")

# sddm
sddm_pkgs=("sddm" "qt5-graphicaleffects" "qt5-quickcontrols2" "qt5-svg")

### X11 ###
x11_pkgs=("xorg-server" "xf86-video-intel" "xf86-input-libinput" "xdotool" "xorg-xinput" "xorg-xrandr" "xorg-xrdb" "arandr" "xidlehook" "xss-lock" "light" "xclip")

### Wayland ###
wayland_pkgs=("wayland" "xorg-server-xwayland" "xdg-desktop-portal-wlr" "wlogout" "wl-randr")

### Packages ###
pkgs=("timeshift" "timeshift-autosnap" "upower" "dunst" "catfish" "btop" "gparted" "grub-customizer" "stacer" "tlpui" "xdg-ninja" "imager-bin"
  "ttf-hack" "ttf-iosevka-nerd" "ttf-roboto" "ttf-roboto-mono" "qt5ct" "papirus-icon-theme" "noto-fonts" "noto-fonts-cjk" "noto-fonts-emoji" "noto-fonts-extra" # "lxappearence"
  "picom" "fastfetch" "cava" "ranger" "nemo" "zathura" "zathura-pdf-mupdf" "lolcat" "flameshot" "obs-studio" "mpv" "mpd" "ncmpcpp" "mpc" # "inkscape" "tenacity-git"
  "neovim" "alacritty" "exa" "rclone" "ripgrep" "tree" "p7zip" "p7zip-gui" "perl-rename"
  "openresolv" "speedtest-cli" "firefox" "telegram-desktop" "bitwarden" "ddgr" "discord_arch_electron" "zoom" "spotify" "realvnc-vnc-viewer" "youtube-dl"
  "code" "github-desktop" "oh-my-git" "sqlite" # "mysql-workbench" "pgadmin4" "postgresql"
)

### GUI-specific ###
# KDE
kde_pkgs=("plasma" "xdg-desktop-portal-kde")

# i3
i3_pkgs=("i3-gaps" "i3status" "i3-resurrect" "betterlockscreen" "rofi" "polybar" "nitrogen")

# Sway
sway_pkgs=("sway" "waybar" "swaybg" "swaylock" "swayidle" "rofi-lbonn-wayland")
