#!/bin/bash

### Display manager ###
# lightdm
lightdm_pkgs=("lightdm" "lightdm-slick-greeter" "lightdm-settings" "light-locker")

# sddm
sddm_pkgs=("sddm" "qt5-graphicaleffects" "qt5-quickcontrols2" "qt5-svg")

### X11 ###
x11_pkgs=("xorg-server" "xf86-video-intel" "xf86-input-libinput" "xdotool" "xorg-xinput" "xorg-xrandr" "xorg-xrdb" "arandr" "xidlehook" "xss-lock" "light" "xclip") # "discord_arch_electron"

### Wayland ###
wayland_pkgs=("wayland" "xorg-server-xwayland" "xdg-desktop-portal-wlr" "wlogout" "wl-randr") # "discord_arch_electron_wayland"

### Packages ###
pkgs=("timeshift" "timeshift-autosnap" "upower" "dunst" "catfish" "gparted" "grub-customizer" "stacer" "tlpui" "xdg-ninja" "imager-bin" "bleachbit"
  "ttf-hack" "ttf-iosevka-nerd" "ttf-roboto" "ttf-roboto-mono" "qt5ct" "papirus-icon-theme"                                                                                                    # "lxappearence"
  "picom" "neofetch" "cava" "ranger" "nemo" "nemo-terminal" "nemo-fileroller" "zathura" "zathura-pdf-mupdf" "libmupdf" "tabbed" "flameshot" "obs-studio" "mpv" "mpd" "mpDris2" "playerctl" "ncmpcpp" "zscroll-git" # "pdfarranger" "pdfshuffler" "inkscape" "tenacity-git"
  "tldr" "neovim" "neovim-remote" "alacritty" "exa" "rclone" "ripgrep" "tree" "perl-rename"
  "openresolv" "speedtest-cli" "firefox" "telegram-desktop" "bitwarden" "ddgr" "discord" "zoom" "spotify" "youtube-dl" # "realvnc-vnc-viewer"
  "code" "oh-my-git" "sqlite"                                                                                       # "mysql-workbench" "pgadmin4" "postgresql" "github-desktop" "gvfs-google" "gnome-control-center"
  # "texlive-core" "texlive-latexextra" "texlive-bibtexextra"
)

### GUI-specific ###
# KDE
kde_pkgs=("plasma" "xdg-desktop-portal-kde")

# i3
i3_pkgs=("i3-gaps" "i3status" "i3-resurrect" "betterlockscreen" "rofi" "polybar" "nitrogen")

# Sway
sway_pkgs=("sway" "waybar" "swaybg" "swaylock" "swayidle" "rofi-lbonn-wayland")
